# Use root/example as user/password credentials
version: '3.1'
services:
  api:
    build: 
      context: ./
    image:  arturogamrod/galactic_federation_api
    restart: always
    ports:
      - 3000:3000  